

/*
 * This source file was generated by the Gradle 'init' task
 */
package studentgrades;
 import java.util.Scanner;

 public class GradeCalculator {
     public static void main(String[] args) {
         // สร้างอ็อบเจกต์ Scanner เพื่อรับข้อมูลจากคีย์บอร์ดบอกไว้แต่น่าจะรู้อยู่แล้วแหละ
         Scanner scanner = new Scanner(System.in);
 
         // รับค่าคะแนนจากที่เราพิมเข้าไป
         System.out.print("Input your score: ");
         int score = scanner.nextInt();
 
         // เช็คค่าคะแนนและแสดงผลลัพธ์เกรด เราจะเอาค่าจาก Score มาเช็คละสร้างตัวแปรมา1 ตัวเพื่อเก็บค่า String ป่าวไว้
         String grade;
         if (score >= 80) {
             grade = "A";
         } else if (score >= 75) {
             grade = "B+";
         } else if (score >= 70) {
             grade = "B";
         } else if (score >= 65) {
             grade = "C+";
         } else if (score >= 60) {
             grade = "C";
         } else if (score >= 55) {
             grade = "D+";
         } else if (score >= 50) {
             grade = "D";
         } else {
             grade = "F";
         }
 
         // Print แสดงค่าตามปกติ ไม่มีอะไรโดยการดึงค่า String ที่สร้างไว้มาแสดงเพื่อสั้นต่อการเขียน
         System.out.println("Your grade is " + grade);
 
         // ปิด scannerปกติไม่มีอะไร
         scanner.close();
     }
 }
    

